funcoes_riscos = {
    "AJUDANTE DE MECÂNICO": {
        "Risco Fisico": "Ruído abaixo do nível de ação, Radiação não ionizante (Incidência de raios solares)",
        "Risco Químico": "Graxa e Óleo Lubrificante",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos moderados Ergonômico",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo, queda de objetos equipamentos ou materiais, corte e escoriações nas mãos, projeção de partículas e substâncias, ataque de animais peçonhentos ou inseto, colisão e abalroamento.",
    },
    "AJUDANTE DE MECÂNICO I": {
        "Risco Fisico": "Ruído abaixo do nível de ação, Radiação não ionizante (Incidência de raios solares)",
        "Risco Químico": "Graxa e Óleo Lubrificante",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos moderados Ergonômico",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo, queda de objetos equipamentos ou materiais, corte e escoriações nas mãos, projeção de partículas e substâncias, ataque de animais peçonhentos ou inseto, colisão e abalroamento.",
    },
    "ALMOXARIFADO": {
        "Risco Fisico": "Ruído abaixo do nível de ação.",
        "Risco Químico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo.",
    },
    "AJUDANTE DE MOTORISTA": {
        "Risco Fisico": "Ruído acima do nível de ação e abaixo do limite de tolerância, Vibração Corpo Inteiro - VCI,\nRadiação não ionizante (Incidência de raios solares)",
        "Risco Químico": "Graxa e Óleo Lubrificante.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo, queda de objetos equipamentos ou materiais, corte e escoriações nas mãos, projeção de partículas e substâncias, ataque de animais peçonhentos ou insetos, colisão e abalroamento.",
    },
    "ANALISTA ADMINISTRATIVO I": {
        "Risco Fisico": "Ruído abaixo do nível de ação.",
        "Risco Químico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves.",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo.",
    },
    "ANALISTA DE DEPARTAMENTO PESSOAL": {
        "Risco Fisico": "Ruído abaixo do nível de ação.",
        "Risco Químico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves.",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo.",
    },
    "ANALISTA FLORESTAL": {
        "Risco Fisico": "Ruído abaixo do nível de ação, Radiação não ionizante (Incidência de raios solares), Calor.",
        "Risco Químico": "Sulfluramida, Glifosato, Imazapyr, Flumioxazina.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves.",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo, queda de objetos equipamentos ou materiais, corte e escoriações nas mãos, projeção de partículas e substâncias, ataque de animais peçonhentos ou inseto, colisão e abalroamento.",
    },
    "ANALISTA FLORESTAL II": {
        "Risco Fisico": "Ruído abaixo do nível de ação, Radiação não ionizante (Incidência de raios solares), Calor.",
        "Risco Químico": "Sulfluramida, Glifosato, Imazapyr, Flumioxazina.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves.",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo, queda de objetos equipamentos ou materiais, corte e escoriações nas mãos, projeção de partículas e substâncias, ataque de animais peçonhentos ou inseto, colisão e abalroamento.",
    },
    "ASSISTENTE ADMINISTRATIVO": {
        "Risco Fisico": "Ruído abaixo do nível de ação.",
        "Risco Químico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves.",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo.",
    },
    "ASSISTENTE ADMINISTRATIVO - APRENDIZ": {
        "Risco Fisico": "Ruído abaixo do nível de ação.",
        "Risco Químico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves.",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo.",
    },
    "ASSISTENTE ADMINISTRATIVO I": {
        "Risco Fisico": "Ruído abaixo do nível de ação.",
        "Risco Químico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves.",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo.",
    },
    "ASSISTENTE ADMINISTRATIVO II": {
        "Risco Fisico": "Ruído abaixo do nível de ação.",
        "Risco Químico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves.",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo.",
    },
    "ASSISTENTE ADMINISTRATIVO III": {
        "Risco Fisico": "Ruído abaixo do nível de ação.",
        "Risco Químico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves.",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo.",
    },
    "ASSISTENTE ADMINISTRATIVO RURAL": {
        "Risco Fisico": "Ruído abaixo do nível de ação.",
        "Risco Químico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves.",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo.",
    },
    "ASSISTENTE DE COMPRAS": {
        "Risco Fisico": "Ruído abaixo do nível de ação.",
        "Risco Químico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves.",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo.",
    },
    "ASSISTENTE DE COMPRAS I": {
        "Risco Fisico": "Ruído abaixo do nível de ação.",
        "Risco Químico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves.",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo.",
    },
    "ASSISTENTE DE RECRUTAMENTO E SELEÇÃO": {
        "Risco Fisico": "Ruído abaixo do nível de ação.",
        "Risco Químico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves.",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo.",
    },
    "AUXILIAR ADMINISTRATIVO": {
        "Risco Fisico": "Ruído abaixo do nível de ação.",
        "Risco Químico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves.",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo.",
    },
    "AUXILIAR DE ALMOXARIFADO": {
        "Risco Fisico": "Ruído abaixo do nível de ação.",
        "Risco Químico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo.",
    },
    "AUXILIAR DE BORRACHEIRO": {
        "Risco Fisico": "Ruído acima do nível de ação e do limite de tolerância, Radiação não ionizante (Incidência de raios solares), Vibração – VMB.",
        "Risco Químico": "Graxa, Óleo lubrificante e cimento de vulcanização",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos moderados",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo, queda de objetos equipamentos ou materiais, corte e escoriações nas mãos, projeção de partículas e substâncias, ataque de animais peçonhentos ou inseto, Colisão e Abalroamento.",
    },
    "AUXILIAR DE ELETRICISTA": {
        "Risco Fisico": "Ruído abaixo do nível de ação, Radiação não ionizante (Incidência de raios solares).",
        "Risco Químico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos Ergonômicos – Leves.",
        "Acidente": "Escorregão e queda do mesmo nível, batidas contra o corpo, cortes e escoriações nas\nmãos, projeção de partículas e substâncias, Queda de objetos, equipamentos ou materiais.",
    },
    "AUXILIAR DE ESCRITÓRIO EM GERAL": {
        "Risco Fisico": "Ruído abaixo do nível de ação.",
        "Risco Químico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves.",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo.",
    },
    "AUXILIAR LIDER DE CAMPO": {
        "Risco Fisico": "Ruído abaixo do nível de ação, Radiação não ionizante (Incidência de raios solares), Calor.",
        "Risco Químico": "Sulfluramida, Glifosato, Imazapyr, Flumioxazina.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos moderados",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo, queda de objetos equipamentos ou materiais, corte e escoriações nas mãos, projeção de partículas e substâncias, colisão e abalroamento, ataque de animais peçonhentos ou inseto.",
    },
    "AUXILIAR DE MECÂNICO": {
        "Risco Fisico": "Ruído abaixo do nível de ação, Radiação não ionizante (Incidência de raios solares)",
        "Risco Químico": "Graxa e Óleo Lubrificante",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos moderados Ergonômico",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo, queda de objetos equipamentos ou materiais, corte e escoriações nas mãos, projeção de partículas e substâncias, ataque de animais peçonhentos ou inseto, colisão e abalroamento.",
    },
    "AUXILIAR DE MECÂNICO I": {
        "Risco Fisico": "Ruído abaixo do nível de ação, Radiação não ionizante (Incidência de raios solares)",
        "Risco Químico": "Graxa e Óleo Lubrificante",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos moderados Ergonômico",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo, queda de objetos equipamentos ou materiais, corte e escoriações nas mãos, projeção de partículas e substâncias, ataque de animais peçonhentos ou inseto, colisão e abalroamento.",
    },
    "AUXILIAR DE MECÂNICO II": {
        "Risco Fisico": "Ruído abaixo do nível de ação, Radiação não ionizante (Incidência de raios solares)",
        "Risco Químico": "Graxa e Óleo Lubrificante",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos moderados Ergonômico",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo, queda de objetos equipamentos ou materiais, corte e escoriações nas mãos, projeção de partículas e substâncias, ataque de animais peçonhentos ou inseto, colisão e abalroamento.",
    },
    "AUXILIAR DE QUALIDADE": {
        "Risco Fisico": "Ruído abaixo do nível de ação.",
        "Risco Químico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo.",
    },
    "BORRACHEIRO": {
        "Risco Fisico": "Ruído acima do nível de ação e do limite de tolerância Radiação não ionizante (Incidência de raios solares), Vibração – VMB.",
        "Risco Químico": "Graxa, Óleo lubrificante e cimento de vulcanização",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos moderados",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo, queda de objetos equipamentos ou materiais, corte e escoriações nas mãos, projeção de partículas e substâncias, ataque de animais peçonhentos ou inseto, Colisão e Abalroamento.",
    },
    "BORRACHEIRO II": {
        "Risco Fisico": "Ruído acima do nível de ação e do limite de tolerância Radiação não ionizante (Incidência de raios solares), Vibração – VMB.",
        "Risco Químico": "Graxa, Óleo lubrificante e cimento de vulcanização",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos moderados",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo, queda de objetos equipamentos ou materiais, corte e escoriações nas mãos, projeção de partículas e substâncias, ataque de animais peçonhentos ou inseto, Colisão e Abalroamento.",
    },
    "BORRACHEIRO III": {
        "Risco Fisico": "Ruído acima do nível de ação e do limite de tolerância Radiação não ionizante (Incidência de raios solares), Vibração – VMB.",
        "Risco Químico": "Graxa, Óleo lubrificante e cimento de vulcanização",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos moderados",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo, queda de objetos equipamentos ou materiais, corte e escoriações nas mãos, projeção de partículas e substâncias, ataque de animais peçonhentos ou inseto, Colisão e Abalroamento.",
    },
    "COORDENADOR FLORESTAL": {
        "Risco Fisico": "Ruído abaixo do nível de ação, Radiação não ionizante (Incidência de raios solares), Calor.",
        "Risco Químico": "Sulfluramida, Glifosato, Imazapyr, Flumioxazina.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves.",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo, queda de objetos equipamentos ou materiais, corte e escoriações nas mãos, projeção de partículas e substâncias, ataque de animais peçonhentos ou inseto, colisão e abalroamento.",
    },
    "ELETRICISTA": {
        "Risco Fisico": "Ruído abaixo do nível de ação, Radiação não ionizante (Incidência de raios solares).",
        "Risco Químico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos Ergonômicos – Leves.",
        "Acidente": "Escorregão e queda do mesmo nível, batidas contra o corpo, cortes e escoriações nas\nmãos, projeção de partículas e substâncias, Queda de objetos, equipamentos ou materiais.",
    },
    "ELETRICISTA AUTOMOTIVO": {
        "Risco Fisico": "Ruído abaixo do nível de ação, Radiação não ionizante (Incidência de raios solares).",
        "Risco Químico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos Ergonômicos – Leves.",
        "Acidente": "Escorregão e queda do mesmo nível, batidas contra o corpo, cortes e escoriações nas\nmãos, projeção de partículas e substâncias, Queda de objetos, equipamentos ou materiais.",
    },
    "ELETRICISTA AUTOMOTIVO II": {
        "Risco Fisico": "Ruído abaixo do nível de ação, Radiação não ionizante (Incidência de raios solares).",
        "Risco Químico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos Ergonômicos – Leves.",
        "Acidente": "Escorregão e queda do mesmo nível, batidas contra o corpo, cortes e escoriações nas\nmãos, projeção de partículas e substâncias, Queda de objetos, equipamentos ou materiais.",
    },
    "ELETRICISTA I": {
        "Risco Fisico": "Ruído abaixo do nível de ação, Radiação não ionizante (Incidência de raios solares).",
        "Risco Químico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos Ergonômicos – Leves.",
        "Acidente": "Escorregão e queda do mesmo nível, batidas contra o corpo, cortes e escoriações nas\nmãos, projeção de partículas e substâncias, Queda de objetos, equipamentos ou materiais.",
    },
    "ELETRICISTA II": {
        "Risco Fisico": "Ruído abaixo do nível de ação, Radiação não ionizante (Incidência de raios solares).",
        "Risco Químico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos Ergonômicos – Leves.",
        "Acidente": "Escorregão e queda do mesmo nível, batidas contra o corpo, cortes e escoriações nas\nmãos, projeção de partículas e substâncias, Queda de objetos, equipamentos ou materiais.",
    },
    "FAXINEIRO": {
        "Risco Fisico": "Ruído abaixo do nível de ação, Calor.",
        "Risco Químico": "Saneantes Domissanitários.",
        "Risco Biológico": "Microrganismos.",
        "Risco Ergonômico": "Aspectos ergonômicos leves.",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo, projeção de partículas e\nsubstâncias.",
    },
    "LIDER DE CAMPO": {
        "Risco Fisico": "Ruído abaixo do nível de ação, Radiação não ionizante (Incidência de raios solares), Calor.",
        "Risco Químico": "Sulfluramida, Glifosato, Imazapyr, Flumioxazina.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves.",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo, queda de objetos equipamentos ou materiais, corte e escoriações nas mãos, projeção de partículas e substâncias, ataque de animais peçonhentos ou inseto, colisão e abalroamento.",
    },
    "LIDER DE CAMPO I": {
        "Risco Fisico": "Ruído abaixo do nível de ação, Radiação não ionizante (Incidência de raios solares), Calor.",
        "Risco Químico": "Sulfluramida, Glifosato, Imazapyr, Flumioxazina.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves.",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo, queda de objetos equipamentos ou materiais, corte e escoriações nas mãos, projeção de partículas e substâncias, ataque de animais peçonhentos ou inseto, colisão e abalroamento.",
    },
    "LIDER DE CAMPO II": {
        "Risco Fisico": "Ruído abaixo do nível de ação, Radiação não ionizante (Incidência de raios solares), Calor.",
        "Risco Químico": "Sulfluramida, Glifosato, Imazapyr, Flumioxazina.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves.",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo, queda de objetos equipamentos ou materiais, corte e escoriações nas mãos, projeção de partículas e substâncias, ataque de animais peçonhentos ou inseto, colisão e abalroamento.",
    },
    "LIDER DE QUALIDADE": {
        "Risco Fisico": "Ruído abaixo do nível de ação.",
        "Risco Químico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo.",
    },
    "MECÂNICO": {
        "Risco Fisico": "Ruído abaixo do nível de ação, Radiação não ionizante (Incidência de raios solares)",
        "Risco Químico": "Graxa e Óleo Lubrificante, Fumos metálicos",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos Ergonômicos – Moderados.",
        "Acidente": "Aspectos ergonômicos moderados",
    },
    "MECÂNICO DE MANUTENÇÃO DE MOTOROÇADEIRAS": {
        "Risco Fisico": "Ruído abaixo do nível de ação, Radiação não ionizante (Incidência de raios solares)",
        "Risco Químico": "Graxa e Óleo Lubrificante, Fumos metálicos",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos Ergonômicos – Moderados.",
        "Acidente": "Aspectos ergonômicos moderados",
    },
    "MECÂNICO ELETRICISTA": {
        "Risco Fisico": "Ruído abaixo do nível de ação, Radiação não ionizante (Incidência de raios solares)",
        "Risco Químico": "Graxa e Óleo Lubrificante, Fumos metálicos",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos Ergonômicos – Moderados.",
        "Acidente": "Aspectos ergonômicos moderados",
    },
    "MECÂNICO I": {
        "Risco Fisico": "Ruído abaixo do nível de ação, Radiação não ionizante (Incidência de raios solares)",
        "Risco Químico": "Graxa e Óleo Lubrificante, Fumos metálicos",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos Ergonômicos – Moderados.",
        "Acidente": "Aspectos ergonômicos moderados",
    },
    "MECÂNICO II": {
        "Risco Fisico": "Ruído abaixo do nível de ação, Radiação não ionizante (Incidência de raios solares)",
        "Risco Químico": "Graxa e Óleo Lubrificante, Fumos metálicos",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos Ergonômicos – Moderados.",
        "Acidente": "Aspectos ergonômicos moderados",
    },
    "MECANICO LIDER": {
        "Risco Fisico": "Ruído abaixo do nível de ação, Radiação não ionizante (Incidência de raios solares)",
        "Risco Químico": "Graxa e Óleo Lubrificante, Fumos metálicos",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos Ergonômicos – Moderados.",
        "Acidente": "Aspectos ergonômicos moderados",
    },
    "MECANICO LUBRIFICADOR": {
        "Risco Fisico": "Ruído abaixo do nível de ação, Radiação não ionizante (Incidência de raios solares)",
        "Risco Químico": "Graxa e Óleo Lubrificante, Fumos metálicos",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos Ergonômicos – Moderados.",
        "Acidente": "Aspectos ergonômicos moderados",
    },
    "MECÂNICO LUBRIFICADOR II": {
        "Risco Fisico": "Ruído abaixo do nível de ação, Radiação não ionizante (Incidência de raios solares)",
        "Risco Químico": "Graxa e Óleo Lubrificante, Fumos metálicos",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos Ergonômicos – Moderados.",
        "Acidente": "Aspectos ergonômicos moderados",
    },
    "MONITOR FLORESTAL I": {
        "Risco Fisico": "Ruído abaixo do nível de ação, Radiação não ionizante (Incidência de raios solares), Calor.",
        "Risco Químico": "Sulfluramida, Glifosato, Imazapyr, Flumioxazina.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves.",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo, queda de objetos equipamentos ou materiais, corte e escoriações nas mãos, projeção de partículas e substâncias, ataque de animais peçonhentos ou inseto, colisão e abalroamento.",
    },
    "MOTORISTA": {
        "Risco Fisico": "Ruído acima do nível de ação e abaixo do limite de tolerância, Vibração Corpo Inteiro - VCI,\nRadiação não ionizante (Incidência de raios solares)",
        "Risco Químico": "Graxa e Óleo Lubrificante.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo, queda de objetos equipamentos ou materiais, corte e escoriações nas mãos, projeção de partículas e substâncias, ataque de animais peçonhentos ou insetos, colisão e abalroamento.",
    },
    "MOTORISTA DE CAMINHÃO - GUINCHO LEVE": {
        "Risco Fisico": "Ruído acima do nível de ação e abaixo do limite de tolerância, Vibração Corpo Inteiro - VCI,\nRadiação não ionizante (Incidência de raios solares)",
        "Risco Químico": "Graxa e Óleo Lubrificante.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo, queda de objetos equipamentos ou materiais, corte e escoriações nas mãos, projeção de partículas e substâncias, ataque de animais peçonhentos ou insetos, colisão e abalroamento.",
    },
    "MOTORISTA DE CAMINHÃO - GUINCHO ": {
        "Risco Fisico": "Ruído acima do nível de ação e abaixo do limite de tolerância, Vibração Corpo Inteiro - VCI,\nRadiação não ionizante (Incidência de raios solares)",
        "Risco Químico": "Graxa e Óleo Lubrificante.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo, queda de objetos equipamentos ou materiais, corte e escoriações nas mãos, projeção de partículas e substâncias, ataque de animais peçonhentos ou insetos, colisão e abalroamento.",
    },
    "MOTORISTA DE CAMINHÃO - GUINCHO II": {
        "Risco Fisico": "Ruído acima do nível de ação e abaixo do limite de tolerância, Vibração Corpo Inteiro - VCI,\nRadiação não ionizante (Incidência de raios solares)",
        "Risco Químico": "Graxa e Óleo Lubrificante.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo, queda de objetos equipamentos ou materiais, corte e escoriações nas mãos, projeção de partículas e substâncias, ataque de animais peçonhentos ou insetos, colisão e abalroamento.",
    },
    "MOTORISTA DE CAMINHÃO - GUINCHO III": {
        "Risco Fisico": "Ruído acima do nível de ação e abaixo do limite de tolerância, Vibração Corpo Inteiro - VCI,\nRadiação não ionizante (Incidência de raios solares)",
        "Risco Químico": "Graxa e Óleo Lubrificante.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo, queda de objetos equipamentos ou materiais, corte e escoriações nas mãos, projeção de partículas e substâncias, ataque de animais peçonhentos ou insetos, colisão e abalroamento.",
    },
    "MOTORISTA I": {
        "Risco Fisico": "Ruído acima do nível de ação e abaixo do limite de tolerância, Vibração Corpo Inteiro - VCI,\nRadiação não ionizante (Incidência de raios solares)",
        "Risco Químico": "Graxa e Óleo Lubrificante.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo, queda de objetos equipamentos ou materiais, corte e escoriações nas mãos, projeção de partículas e substâncias, ataque de animais peçonhentos ou insetos, colisão e abalroamento.",
    },
    "MOTORISTA III": {
        "Risco Fisico": "Ruído acima do nível de ação e abaixo do limite de tolerância, Vibração Corpo Inteiro - VCI,\nRadiação não ionizante (Incidência de raios solares)",
        "Risco Químico": "Graxa e Óleo Lubrificante.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo, queda de objetos equipamentos ou materiais, corte e escoriações nas mãos, projeção de partículas e substâncias, ataque de animais peçonhentos ou insetos, colisão e abalroamento.",
    },
    "RECEPCIONISTA": {
        "Risco Fisico": "Ruído abaixo do nível de ação.",
        "Risco Químico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves.",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo.",
    },
    "SERVIÇOS GERAIS": {
        "Risco Fisico": "Ruído abaixo do nível de ação, Radiação não ionizante (Incidência de raios solares), Calor.",
        "Risco Químico": "Sulfluramida, Glifosato, Imazapyr, Flumioxazina, Gasolina, Óleo dois tempos e Óleo\nlubrificante.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos Ergonômicos – Moderados.",
        "Acidente": "Escorregão e queda do mesmo nível, batidas contra o corpo, queda de objetos equipamentos ou materiais, ataque de animais peçonhentos ou insetos, cortes e escoriações nas mãos, projeção de partículas e substâncias.",
    },
    "SOLDADOR": {
        "Risco Fisico": "Ruído abaixo do nível de ação, Radiação não ionizante (Incidência de raios solares).",
        "Risco Químico": "Fumos Metálicos.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos Ergonômicos – Moderados.",
        "Acidente": "Escorregão e queda do mesmo nível, batidas contra o corpo, corte e escoriações nas mãos, projeção de partículas e substancias, queda de objetos sobre os membros inferiores.",
    },
    "SOLDADOR MECÂNICO": {
        "Risco Fisico": "Ruído abaixo do nível de ação, Radiação não ionizante (Incidência de raios solares).",
        "Risco Químico": "Fumos Metálicos.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos Ergonômicos – Moderados.",
        "Acidente": "Escorregão e queda do mesmo nível, batidas contra o corpo, corte e escoriações nas mãos, projeção de partículas e substancias, queda de objetos sobre os membros inferiores.",
    },
    "SOLDADOR MECÂNICO I ": {
        "Risco Fisico": "Ruído abaixo do nível de ação, Radiação não ionizante (Incidência de raios solares).",
        "Risco Químico": "Fumos Metálicos.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos Ergonômicos – Moderados.",
        "Acidente": "Escorregão e queda do mesmo nível, batidas contra o corpo, corte e escoriações nas mãos, projeção de partículas e substancias, queda de objetos sobre os membros inferiores.",
    },
    "SUPERVISOR DE MANUTENÇÃO": {
        "Risco Fisico": "Ruído abaixo do nível de ação,\nRadiação não ionizante (Incidência de raios solares)",
        "Risco Químico": "Graxa e Óleo Lubrificante",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos moderados",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo, queda de objetos equipamentos ou materiais, corte e escoriações nas mãos, projeção de partículas e substâncias, ataque de animais peçonhentos ou inseto, colisão e abalroamento.",
    },
    "SUPERVISOR DE SEGURANÇA DO TRABALHO": {
        "Risco Fisico": "Ruído abaixo do nível de ação, Radiação não ionizante (Incidência de raios solares)",
        "Risco Químico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves.",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo, Colisão e abalroamento, Projeção de partícula e substâncias, Queda de objetos equipamentos ou materiais",
    },
    "SUPERVISOR DE SEGURANÇA DO TRABALHO I": {
        "Risco Fisico": "Ruído abaixo do nível de ação, Radiação não ionizante (Incidência de raios solares)",
        "Risco Químico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves.",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo, Colisão e abalroamento, Projeção de partícula e substâncias, Queda de objetos equipamentos ou materiais",
    },
    "SUPERVISOR DE SEGURANÇA DO TRABALHO II": {
        "Risco Fisico": "Ruído abaixo do nível de ação, Radiação não ionizante (Incidência de raios solares)",
        "Risco Químico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves.",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo, Colisão e abalroamento, Projeção de partícula e substâncias, Queda de objetos equipamentos ou materiais",
    },
    "SUPERVISOR DE TI": {
        "Risco Fisico": "Ruído abaixo do nível de ação.",
        "Risco Químico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves.",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo, queda de objetos equipamentos ou materiais.",
    },
    "SUPERVISOR FINANCEIRO": {
        "Risco Fisico": "Ruído abaixo do nível de ação.",
        "Risco Químico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves.",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo.",
    },
    "SUPERVISOR FLORESTAL": {
        "Risco Fisico": "Ruído abaixo do nível de ação, Radiação não ionizante (Incidência de raios solares), Calor.",
        "Risco Químico": "Sulfluramida, Glifosato, Imazapyr, Flumioxazina.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves.",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo, queda de objetos equipamentos ou materiais, corte e escoriações nas mãos, projeção de partículas e substâncias, ataque de animais peçonhentos ou inseto, colisão e abalroamento.",
    },
    "TECNICO DE OPERAÇÕES FLORESTAIS": {
        "Risco Fisico": "Ruído abaixo do nível de ação, Radiação não ionizante (Incidência de raios solares), Calor.",
        "Risco Químico": "Sulfluramida, Glifosato, Imazapyr, Flumioxazina.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves.",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo, queda de objetos equipamentos ou materiais, corte e escoriações nas mãos, projeção de partículas e substâncias, ataque de animais peçonhentos ou inseto, colisão e abalroamento.",
    },
    "TECNICO EM SEGURANÇA DO TRABALHO": {
        "Risco Fisico": "Ruído abaixo do nível de ação, Radiação não ionizante (Incidência de raios solares)",
        "Risco Químico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves.",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo, Colisão e abalroamento, Projeção de partícula e substâncias, Queda de objetos equipamentos ou materiais",
    },
    "TRABALHADOR FLORESTAL": {
        "Risco Fisico": "Ruído abaixo do nível de ação, Radiação não ionizante (Incidência de raios solares), Calor.",
        "Risco Químico": "Sulfluramida, Glifosato, Imazapyr, Flumioxazina.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos Ergonômicos – Moderados.",
        "Acidente": "Escorregão e queda do mesmo nível, batidas contra o corpo, queda de objetos equipamentos ou materiais, ataque de animais peçonhentos ou insetos, cortes e escoriações nas mãos, projeção de partículas e substâncias.",
    },
    "TRABALHADOR RURAL POLIVALENTE": {
        "Risco Fisico": "Ruído abaixo do nível de ação, Radiação não ionizante (Incidência de raios solares), Calor.",
        "Risco Químico": "Sulfluramida, Glifosato, Imazapyr, Flumioxazina, Gasolina, Óleo dois tempos e Óleo\nlubrificante.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos Ergonômicos – Moderados.",
        "Acidente": "Escorregão e queda do mesmo nível, batidas contra o corpo, queda de objetos equipamentos ou materiais, ataque de animais peçonhentos ou insetos, cortes e escoriações nas mãos, projeção de partículas e substâncias.",
    },
    "TRATORISTA": {
        "Risco Fisico": "Ruído acima do nível de ação e abaixo do limite de tolerância, Vibração Corpo Inteiro - VCI,\nRadiação não ionizante (Incidência de raios solares)",
        "Risco Químico": "Sulfluramida, Glifosato, Imazapyr, Flumioxazina, Graxa e Óleo Lubrificante.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo, queda de objetos equipamentos ou materiais, corte e escoriações nas mãos, projeção de partículas e substâncias, ataque de animais peçonhentos ou insetos, colisão e abalroamento.",
    },
    "TRATORISTA I": {
        "Risco Fisico": "Ruído acima do nível de ação e abaixo do limite de tolerância, Vibração Corpo Inteiro - VCI,\nRadiação não ionizante (Incidência de raios solares)",
        "Risco Químico": "Sulfluramida, Glifosato, Imazapyr, Flumioxazina, Graxa e Óleo Lubrificante.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo, queda de objetos equipamentos ou materiais, corte e escoriações nas mãos, projeção de partículas e substâncias, ataque de animais peçonhentos ou insetos, colisão e abalroamento.",
    },
    "VIGIA": {
        "Risco Fisico": "Ruído abaixo do nível de ação.",
        "Risco Químico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves.",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo, projeção de partículas e\nsubstâncias.",
    },
    "ZELADOR": {
        "Risco Fisico": "Ruído abaixo do nível de ação.",
        "Risco Químico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Biológico": "Não foram encontradas fontes de exposição ao risco.",
        "Risco Ergonômico": "Aspectos ergonômicos leves.",
        "Acidente": "Escorregão e quedas do mesmo nível, batidas contra o corpo, projeção de partículas e\nsubstâncias.",
    },
}


cargos_nomes = ['AJUDANTE DE MECÂNICO', 'AJUDANTE DE MECÂNICO I', 'ALMOXARIFADO', 'AJUDANTE DE MOTORISTA', 'ANALISTA ADMINISTRATIVO I', 'ANALISTA DE DEPARTAMENTO PESSOAL', 'ANALISTA FLORESTAL', 'ANALISTA FLORESTAL II', 'ASSISTENTE ADMINISTRATIVO', 'ASSISTENTE ADMINISTRATIVO - APRENDIZ', 'ASSISTENTE ADMINISTRATIVO I', 'ASSISTENTE ADMINISTRATIVO II', 'ASSISTENTE ADMINISTRATIVO III', 'ASSISTENTE ADMINISTRATIVO RURAL', 'ASSISTENTE DE COMPRAS', 'ASSISTENTE DE COMPRAS I', 'ASSISTENTE DE RECRUTAMENTO E SELEÇÃO', 'AUXILIAR ADMINISTRATIVO', 'AUXILIAR DE ALMOXARIFADO', 'AUXILIAR DE BORRACHEIRO', 'AUXILIAR DE ELETRICISTA', 'AUXILIAR DE ESCRITÓRIO EM GERAL', 'AUXILIAR LIDER DE CAMPO', 'AUXILIAR DE MECÂNICO', 'AUXILIAR DE MECÂNICO I', 'AUXILIAR DE MECÂNICO II', 'AUXILIAR DE QUALIDADE', 'BORRACHEIRO', 'BORRACHEIRO II', 'BORRACHEIRO III', 'COORDENADOR FLORESTAL', 'ELETRICISTA', 'ELETRICISTA AUTOMOTIVO', 'ELETRICISTA AUTOMOTIVO II', 'ELETRICISTA I', 'ELETRICISTA II', 'FAXINEIRO', 'LIDER DE CAMPO', 'LIDER DE CAMPO I', 'LIDER DE CAMPO II', 'LIDER DE QUALIDADE', 'MECÂNICO', 'MECÂNICO DE MANUTENÇÃO DE MOTOROÇADEIRAS', 'MECÂNICO ELETRICISTA', 'MECÂNICO I', 'MECÂNICO II', 'MECANICO LIDER', 'MECANICO LUBRIFICADOR', 'MECÂNICO LUBRIFICADOR II', 'MONITOR FLORESTAL I', 'MOTORISTA', 'MOTORISTA DE CAMINHÃO - GUINCHO LEVE', 'MOTORISTA DE CAMINHÃO - GUINCHO ', 'MOTORISTA DE CAMINHÃO - GUINCHO II', 'MOTORISTA DE CAMINHÃO - GUINCHO III', 'MOTORISTA I', 'MOTORISTA III', 'RECEPCIONISTA', 'SERVIÇOS GERAIS', 'SOLDADOR', 'SOLDADOR MECÂNICO', 'SOLDADOR MECÂNICO I ', 'SUPERVISOR DE MANUTENÇÃO', 'SUPERVISOR DE SEGURANÇA DO TRABALHO', 'SUPERVISOR DE SEGURANÇA DO TRABALHO I', 'SUPERVISOR DE SEGURANÇA DO TRABALHO II', 'SUPERVISOR DE TI', 'SUPERVISOR FINANCEIRO', 'SUPERVISOR FLORESTAL', 'TECNICO DE OPERAÇÕES FLORESTAIS', 'TECNICO EM SEGURANÇA DO TRABALHO', 'TRABALHADOR FLORESTAL', 'TRABALHADOR RURAL POLIVALENTE', 'TRATORISTA', 'TRATORISTA I', 'VIGIA', 'ZELADOR']


